# Jekyll Configuration for Interview Prep Documentation

# Site settings
title: "Interview Prep Documentation"
description: "Comprehensive guides for JavaScript, TypeScript, and React Native interview preparation"
baseurl: ""
url: ""

# Build settings
markdown: commonmark
highlighter: rouge
theme: minima

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - .git
  - .gitignore
  - .DS_Store
  - Thumbs.db

# Include files
include:
  - _redirects

# Collections
collections:
  javascript:
    output: true
    permalink: /:collection/:name/
  typescript:
    output: true
    permalink: /:collection/:name/
  react-native:
    output: true
    permalink: /:collection/:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "javascript"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "typescript"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "react-native"
    values:
      layout: "default"

# Kramdown settings - disable Liquid processing in code blocks
# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Liquid settings - be very permissive
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# Safe mode to prevent arbitrary code execution
safe: true

# Source directory
source: .

# Destination directory
destination: ./_site

# Incremental build
incremental: false

# Show drafts
show_drafts: false

# Limit posts
limit_posts: 0

# Future posts
future: false

# Unpublished posts
unpublished: false

# Timezone
timezone: null

# Encoding
encoding: utf-8

# Markdown extensions
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Textile extensions
textile_ext: "textile"

# Exclude from processing
exclude_from_processing:
  - node_modules
  - vendor
  - .git
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
